### ISSUE TITLE
Implement Rows

### ISSUE THREAD

**Issue by McTano** [McTano/Rudolf#35]
1. We need to be able to mark each node with its "row" (which will be 1 greater than whatever the last "row" created was.
2. Nodes in the tree should be spaced vertically so that they are displayed alongside nodes on other branches which are in the same row.

This will allow us to associate each node with a reference back to the node which we resolved by creating it.

**Comment by kylemas** [comment]
So the "row" would be a similar idea to the values we gave last time to each node to connect them?

**Comment by McTano** [comment]
Kind of. It depends what you mean by "similar idea".

The idea is that the rows of the tree are numbered, like so:

```
1.          P           Ass.
2.          Q           Ass.
3.      ~(P /\ Q)       Ass.
        /        \
4.     ~P        ~Q     (3 ~/\E)
```
So we can tell that the ~P and ~Q nodes were created to resolve the formula on row 3.
There are better examples in the`for-all-x` textbook.

**Comment by kylemas** [comment]
Okay, got it!

**Comment by kylemas** [comment]
Hey Tristan, I did some work on this last week but was not able to continue much this week due to midterms / other commitments.

Right now, I have the rows showing up though not as expected. What I did was have an anchor tag to display the node row (which I've assigned to each node) inside the NodeView. However, it's showing up with each node since I have it inside the div of the node id. I've tried a few other ways to implement this but I haven't been able to succeed in getting it to appear only per row. 

Was wondering if you could offer a different perspective on this?

**Comment by kylemas** [comment]
Here are some screenshots. 
<img width="912" alt="Screen Shot 2019-10-27 at 10 51 11 PM" src="https://user-images.githubusercontent.com/34122775/67654923-4a1f4d80-f90c-11e9-8d38-5f3128873996.png">
![Uploading Screen Shot 2019-10-27 at 10.50.44 PM.png…]()

**Comment by McTano** [comment]
@kylemas 
If you want me to take a look at your code, you should open a pull request. That's what they're for. If it's not ready to merge, just mark it as a "draft pull request" when you create it.

**Comment by kylemas** [comment]
@McTano 
Hey, sorry about that, completely forgot! Will open one up now. 

Thanks!
